class AgreementTerminalsDeu:
    def __init__(self):

        self.terminals = {
            "CF": ["die"],
            "CM": ["der"],
            "CN": ["das"],
            "DF": ["die"],
            "DM": ["der"],
            "DN": ["das"],
            "PRM": ["das ist"],
            "MSC": [  # main subject complementizer
                "der Autor den",
                "der Pilot den",
                "der Chirurg den",
                "der Bauer den",
                "der Geschäftsführer den",
                "der Kunde den",
                "der Offizier den",
                "der Lehrer den",
                "der Gesetzgeber den",
                "der Berater den",
            ],
            "MS": [  # main subject
                "der Autor",
                "der Pilot",
                "der Chirurg",
                "der Bauer",
                "der Geschäftsführer",
                "der Kunde",
                "der Offizier",
                "der Lehrer",
                "der Gesetzgeber",
                "der Berater",
            ],
            "NSC": [  # nonce subject complementizer
                "der Bral den",
                "das Kach das",
                "die Klot die",
                "der Mur den",
                "das Nuhl das",
                "die Pind die",
                "der Pisch den",
                "das Pund das",
                "die Raun die",
                "der Spand den",
                "das Spert das",
                "die Vag die",
                "der Bnaupf den",
                "das Bneik das",
                "die Bnöhk die",
                "der Fnahf den",
                "das Fneik das",
                "die Fnöhk die",
                "der Plaupf den",
                "das Pleik das",
                "die Pläk die",
                "der Pnähf den",
                "das Pröng das",
                "die Snauk die",
            ],
            "NS": [  # nonce subject
                "der Bral",
                "das Kach",
                "die Klot",
                "der Mur",
                "das Nuhl",
                "die Pind",
                "der Pisch",
                "das Pund",
                "die Raun",
                "der Spand",
                "das Spert",
                "die Vag",
                "der Bnaupf",
                "das Bneik",
                "die Bnöhk",
                "der Fnahf",
                "das Fneik",
                "die Fnöhk",
                "der Plaupf",
                "das Pleik",
                "die Pläk",
                "der Pnähf",
                "das Pröng",
                "die Snauk",
            ],
            "ES": [  # embedded subjects
                "der Wächter",
                "der Koch",
                "der Architekt",
                "der Schlittschuhläufer",
                "der Tänzer",
                "der Minister",
                "der Taxifahrer",
                "der Assistent",
                "der Vorsitzender",
                "der Schauspieler",
            ],
            "ESD": [
                "dem Wächter",
                "dem Koch",
                "dem Architekten",
                "dem Schlittschuhläufer",
                "dem Tänzer",
                "dem Minister",
                "dem Taxifahrer",
                "dem Assistenten",
                "dem Vorsitzender",
                "dem Schauspieler",
            ],
            "IS": [  # inanimate main subjects
                "der Film",
                "das Buch",
                "das Spiel",
                "das Lied",
                "das Bild",
                "das Gemälde",
                "der Roman",
                "das Gedicht",
                "die Serie",
            ],
            "MSF": [
                "Autorin",
                "Pilotin",
                "Chirurgin",
                "Bäuerin",
                "Geschäftsführerin",
                "Kundin",
                "Offizierin",
                "Lehrerin",
                "Gesetzgeberin",
                "Beraterin",
            ],
            "ESF": [
                "Wächterin",
                "Köchin",
                "Architektin",
                "Schlittschuhläuferin",
                "Tänzerin",
                "Ministerin",
                "Taxifahrerin",
                "Assistentin",
                "Vorsitzende",
                "Schauspielerin",
            ],
            "ESFD": [
                "der Wächterin",
                "der Köchin",
                "der Architektin",
                "der Schlittschuhläuferin",
                "der Tänzerin",
                "der Ministerin",
                "der Taxifahrerin",
                "der Assistentin",
                "der Vorsitzender",
                "der Schauspielerin",
            ],
            "ISM": [
                "Film",  # die Filme
                "Text",  # die Texte
                "Spielwürfel",  # die Spielwürfel
                "Gesang",  # die Gesänge
                "Stift",  # die Stifte
                "Rahmen",  # die Rahmen
                "Roman",  # die Romane
                "Vers",  # die Verse
                "Fehrnseher",  # die Fehrnseher
            ],
            "ISF": [
                "Serie",  # die Serien
                "Zeitung",  # die Zeitungen
                "Spielfigur",  # die Spielfiguren
                "Kamera",  # die Kameras
                "Symphonie",
                "Farbe",  # die Farben
                "Leinwand",  # die Leinwände
                "Seite",  # die Seiten
                "Dichtung",  # die Dichtungen
            ],
            "MSN": [
                "Kaninchen",
                "Stinktier",
                "Mammut",
                "Lama",
                "Reh",
                "Rentier",
                "Känguru",
                "Krokodil",
                "Schwein",
                "Pferd",
            ],
            "ESN": [
                "Stachelschwein",
                "Meerschweinchen",
                "Schaf",
                "Huhn",
                "Einhorn",
                "Eichhörnchen",
                "Chamäleon",
                "Kamel",
                "Wiesel",
                "Murmeltier",
            ],
            "ESND": [
                "dem Stachelschwein",
                "dem Meerschweinchen",
                "dem Schaf",
                "dem Huhn",
                "dem Einhorn",
                "dem Eichhörnchen",
                "dem Chamäleon",
                "dem Kamel",
                "dem Wiesel",  # TODO: check
                "dem Murmeltier",
            ],
            "ISN": [  # inanimate main subjects
                "Video",
                "Buch",
                "Spiel",
                "Lied",
                "Bild",
                "Gemälde",
                "Kinderbuch",
                "Gedicht",
                "Programm",
            ],
            "NSB": [  # nonce subject w/o determiner
                "Bral",
                "Kach",
                "Klot",
                "Mur",
                "Nuhl",
                "Pind",
                "Pisch",
                "Pund",
                "Raun",
                "Spand",
                "Spert",
                "Vag",
                "Bnaupf",
                "Bneik",
                "Bnöhk",
                "Fnahf",
                "Fneik",
                "Fnöhk",
                "Plaupf",
                "Pleik",
                "Pläk",
                "Pnähf",
                "Pröng",
                "Snauk",
            ],
            "ISC": [  # inanimate main subjects + complementizer
                "der Film den",
                "das Buch das",
                "das Spiel das",
                "das Lied das",
                "das Bild das",
                "das Gemälde das",
                "der Roman den",
                "das Gedicht das",
                "die Serie die",
            ],
            "MV": [  # main verb
                "spielt",
                "läuft",
                "singt",
                "ist groß",
                "ist alt",
                "ist jung",
                "ist klein",
            ],
            "EV": ["mag", "kennt", "schätzt", "liebt"],  # embedded verb
            "IV": [  # inanimate verb
                "ist gut",
                "ist schlecht",
                "ist neu",
                "ist beliebt",
                "ist unbeliebt",
                "macht Leute glücklich",
                "interessiert Leute",
            ],
            "P": [  # prepositions
                "neben",
                "hinter",
                "vor",
                "nahe bei",
                "seitlich von",
                "gegenüber von",
            ],
            "IP": ["von"],  # inanimate prepositions
            "BS": ["der Mechaniker", "der Banker"],  # sent. comp. subjects
            "BSF": ["Mechanikerin", "Bankerin"],
            "BSN": ["Walross", "Zebra"],
            "BV": ["sagte", "dachte", "rief"],  # sent. comp. verbs
            "AND": ["und"],  # the word and lol
            "LMV": [  # long main verbs
                "spricht viele verschiedene Fremdsprachen",
                "sieht gerne Fernsehserien",
                "ist dreiundzwanzig Jahre alt",
                "spielt gerne Tennis mit Kollegen",
                "schreibt jeden Tag in ein Tagebuch",
            ],
        }
