class AgreementTerminalsEng:
    def __init__(self):
        self.terminals = {
            "D": ["the"],
            "IC": ["that"],
            "C": ["that"],
            "PRM": ["this is"],
            "MS": [
                "author",
                "pilot",
                "surgeon",
                "farmer",
                "manager",
                "customer",
                "officer",
                "teacher",
                "senator",
                "consultant",
            ],
            "NS": [
                "tor",
                "gutch",
                "lun",
                "niz",
                "cra",
                "heaf",
                "zib",
                "bik",
                "tass",
                "spow",
                "naz",
                "bod",
                "tas",
            ],
            "ES": [
                "guard",
                "chef",
                "architect",
                "skater",
                "dancer",
                "minister",
                "taxi driver",
                "assistant",
                "executive",
                "parent",
            ],
            "IS": [
                "movie",
                "book",
                "game",
                "song",
                "picture",
                "painting",
                "novel",
                "poem",
                "show",
            ],
            "MV": [
                "laughs",
                "runs",
                "smiles",
                "is tall",
                "is old",
                "is young",
                "is short",
            ],
            "EV": ["likes", "looks up to", "hates", "loves"],
            "IV": [
                "is good",
                "is bad",
                "is new",
                "is popular",
                "is unpopular",
                "brings joy to people",
                "interests people",
            ],
            "P": [
                "next to",
                "behind",
                "in front of",
                "near",
                "to the side of",
                "across from",
            ],
            "IP": ["from", "by"],
            "BS": ["mechanic", "banker"],
            "BV": ["said", "thought", "knew"],
            "AND": ["and"],
            "ANPHR": ["himself", "herself"],
            "LMV": [
                "knows many different foreign languages",
                "likes to watch television shows",
                "is twenty three years old",
                "enjoys playing tennis with colleagues",
                "writes in a journal every day",
            ],
        }
