class AgreementTerminalsFra:
    def __init__(self):
        self.terminals = {
            "C": ["que"],
            "PRM": ["c'est"],
            "MS": [
                "l'auteur",
                "le pilote",
                "le chirurgien",
                "le fermier",
                "le gérant",
                "l'officier",
                "le professeur",
                "le sénateur",
                "le conseiller",
            ],
            "MSF": ["la cliente"],
            "NS": [
                "le elque",
                "le tradantain",
                "le mobeau",
                "le quentouvre",
                "le voin",
                "le ruttachât",
                "le maldème",
                "le démin",
                "le vertaintour",
                "le frirème",
                "le foité",
                "le quentouvrail",
                "le neleau",
                "le déminal",
                "le bouchanceau",
                "le vertaintourail",
                "le foiteau",
                "le ressier",
            ],
            "NSF": ["la nelle", "la pelquis", "la gâtris", "la prièrepette"],
            "ES": [
                "le gardien",
                "le cuisinier",
                "l'architecte",
                "le patineur",
                "le danseur",
                "le ministre",
                "le conducteur",
                "l'assistant",
                "le président",
                "l'acteur",
            ],
            "IS": ["le film", "le livre", "le jeu", "le roman", "le poème"],
            "ISF": ["la chanson", "la peinture", "l'image", "la série"],
            "MV": [
                "court",
                "chante",
                "joue",
                "est grand",
                "est vieux",
                "est jeune",
                "est petit",
            ],
            "MVF": [
                "court",
                "chante",
                "joue",
                "est grande",
                "est vieille",
                "est jeune",
                "est petite",
            ],
            "EV": ["aime", "apprécie", "connaît", "sert"],
            "EVP": ["aiment", "apprécient", "connaissent", "servent"],
            "IV": [
                "est bon",
                "est mauvais",
                "est nouveau",
                "est populaire",
                "est impopulaire",
                "rend les gens contents",
                "intéresse les gens",
            ],
            "IVF": [
                "est bonnes",
                "est mauvaise",
                "est nouvelle",
                "est populaire",
                "est impopulaire",
                "rend les gens contents",
                "intéresse les gens",
            ],
            "P": [
                "à côté de",
                "derrière",
                "devant",
                "près de",
                "sur le côté de",
                "en face de",
            ],
            "IP": ["de"],
            "BS": ["le mécanicien", "le banquier"],
            "BV": ["disait", "pensait", "savait"],
            "BVP": ["disaient", "pensaient", "savaient"],
            "AND": ["et"],
            "LMV": [
                "parle beaucoup de langues étrangères",
                "aime voir des séries télévisées",
                "a vingt-trois ans",
                "aime jouer au tennis avec des collègues",
                "écrit dans un journal tous les jours",
            ],
            "LMVP": [
                "parlent beaucoup de langues étrangères",
                "aiment voir des séries télévisées",
                "ont vingt-trois ans",
                "aiment jouer au tennis avec des collègues",
                "écrivent dans un journal tous les jours",
            ],
        }
